resources:
  - name: custom_image_repo
    type: GitRepo
    configuration:
      path: bindushree16/test1
      gitProvider: github

pipelines:
  - name: bash_pipeline
    steps:
      - name: push_custom_image
        type: Bash
        configuration:
          integrations:
            - name: docker
          inputResources:
            - name: custom_image_repo
        execution:
          onExecute:
            - cd $res_custom_image_repo_resourcePath
#             - sudo docker build -t shippabledocker/jfreq:run_id .
#             - sudo docker push shippabledocker/jfreq:$run_id
            
      - name: custom_images_bash
        type: Bash
        configuration:
          inputSteps:
            - name: push_custom_image
#           runtime:            
#             type: image
#             image:
#               custom:
#                 name: shippabledocker/jfreq
#                 tag: latest
        execution:
          onExecute:
            - echo "Executing testBash.."
            - restore_cache_files pipeline_state_cache cache.txt
            - add_pipeline_variables pipelineId=$pipeline_id
            - add_run_variables runId=$run_number	
            - echo "state=$run_number" > cache.txt
            - add_cache_files cache.txt pipeline_state_cache
            - echo "state=$run_number" > pipeline_state.txt
            - add_pipeline_files pipeline_state.txt pipeline_state_file
            - echo "state=$run_number" > run_state.txt
            - add_run_files run_state.txt run_state_file
            
      - name: restoreStateBash
        type: Bash
        configuration:
          inputSteps:
            - name: custom_images_bash
          #runtime:            
          ##  type: image
          #  image:
          #    custom:
          #      name: shippabledocker/jfreq
           #     tag: latest
        execution:
          onExecute:
            - echo "Executing restoreBash.."
            - restore_pipeline_files pipeline_state_file pipeline_state.txt
            - restore_run_files run_state_file run_state.txt
